/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DevOpsTest;

import com.mitchtalmadge.asciidata.graph.ASCIIGraph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // The series should be an array of doubles.
        double[] sinWaveSeries = new double[120];
        
        // Calculate the Sin Wave.
        for (int i = 0; i < sinWaveSeries.length; i++)
            sinWaveSeries[i] = 15 * Math.sin(i * ((Math.PI * 4) / sinWaveSeries.length));
        
        // Plot and output the graph.
        System.out.println(ASCIIGraph.fromSeries(sinWaveSeries).withNumRows(15).plot());
    }
}
